### ISSUE TITLE
Colored cell contents

### ISSUE THREAD

**Issue by guigui64** [guigui64/stybulate#4]
take ANSI escape sequences into account when calculating width.

**Comment by joshtriplett** [comment]
I would suggest having a trait for "formatted text", which requires `Display`, provides a method `fn unformatted_text(&self) -> String` that returns the text minus the formatting, and provides a method `fn substring(&self, start: usize, end: usize) -> Self` that returns a subset of the string while preserving the formatting. You can have a trivial implementation for `String`, and then implementations for crates like `ansi_term` (opted in by feature-flag, so that people not using them don't have an extra dependency).

**Comment by guigui64** [comment]
Good idea!
In the meantime, I started having a look at it and found an obstacle:

```rust
fn main() {
    let strip = |s: &str| {
        String::from(std::str::from_utf8(&strip_ansi_escapes::strip(s).unwrap()).unwrap())
    };
    let s = "spam \x1b[31meggs\x1b[0m";
    println!("|{:>11}|", strip(s));
    println!("|{:>11}|", s);
}
```
Will print:
```text
|  spam eggs|        # all in black
|spam eggs|          # eggs in red
```

So it seems the str formatting does not work for strings containing ANSI escape sequences...
Help wanted!

**Comment by AmatanHead** [comment]
This is the same width issue. String formatting calculates width by counting codepoints. ANSI escape sequence consists of at least three codepoints. So, you'll have to format strings by yourself, it seems.
